// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ClipboardController from "./clipboard_controller"
application.register("clipboard", ClipboardController)

import MemoryChildrenController from "./memory_children_controller"
application.register("memory-children", MemoryChildrenController)

import ScrollRevealController from "./scroll_reveal_controller"
application.register("scroll-reveal", ScrollRevealController)

import MemoryImagePreviewController from "./memory_image_preview_controller"
application.register("memory-image-preview", MemoryImagePreviewController)

import AvatarPreviewController from "./avatar_preview_controller"
application.register("avatar-preview", AvatarPreviewController)

import ProcessingModalController from "./processing_modal_controller"
application.register("processing-modal", ProcessingModalController)
