// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ClipboardController from "./clipboard_controller"
application.register("clipboard", ClipboardController)

import MemoryChildrenController from "./memory_children_controller"
application.register("memory-children", MemoryChildrenController)

import ScrollRevealController from "./scroll_reveal_controller"
application.register("scroll-reveal", ScrollRevealController)
