# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "ja-JP"

# レビューの“口調”を揃える（短く・根拠と代替案）
tone_instructions: "丁寧語で、指摘は根拠→影響→代替案の順に簡潔に。推測は推測と明記してください。"

reviews:
  # 最初はchill推奨（assertiveは“細かい指摘も増えやすい”）
  profile: "chill"

  # PR要約を有効に（チームの合意形成が速くなる）
  high_level_summary: true

  # “遊び”はまず切る（必要なら後でON）
  poem: false

  # PR内のコメントにAIエージェント向けの修正プロンプトを含める
  enable_prompt_for_ai_agents: true

  # 生成物・成果物・依存ロックなど「見てもノイズになりやすい」ものを除外
  path_filters:
    - "!dist/**"
    - "!build/**"
    - "!coverage/**"
    - "!**/*.lock"
    - "!**/*.min.*"

  # ディレクトリ単位でレビュー観点を追加（例：フロント/バックで見るべき点が違う）
  # path_instructions:
  #  - path: "frontend/**"
  #    instructions: "React/TypeScriptは、状態管理の単純化・依存配列・例外系のUI崩れを重点的に確認してください。"
  #  - path: "backend/**"
  #    instructions: "境界条件、入力バリデーション、ログの粒度、例外の握りつぶしがないかを重点的に確認してください。"

  auto_review:
    enabled: true
    drafts: false

    # “WIP/作業中” は自動レビューしない（通知荒れの最大原因を潰す）
    labels:
      - "!wip"
      - "!do-not-review"

    # タイトルに特定キーワードが含まれる場合もスキップ
    ignore_title_keywords:
      - "WIP"
      - "DO NOT MERGE"
      - "DRAFT"

chat:
  # PR上での対話を前提にするならON（不要ならfalseでもOK）
  auto_reply: true

# ベースブランチに応じた回答をする場合、指定（例：develop/main）
base_branches:
  - develop

